### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group' 

### ISSUE THREAD

**Issue by ddfabbro** [ddfabbro/translatorbot#3]
```
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/slackbot/dispatcher.py", line 55, in _dispatch_msg_handler
    func(Message(self._client, msg), *args)
  File "/home/ubuntu/mybot/translatorbot/plugins.py", line 29, in all_replies
    translate(message)
  File "/home/ubuntu/mybot/translatorbot/plugins.py", line 11, in translate
    if translator.detect(msg_in).lang == "en":
  File "/home/ubuntu/.local/lib/python3.8/site-packages/googletrans/client.py", line 255, in detect
    data = self._translate(text, 'en', 'auto', kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/googletrans/client.py", line 78, in _translate
    token = [self.token_acquirer.do](http://self.token_acquirer.do/)(text)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/googletrans/gtoken.py", line 194, in do
    self._update()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/googletrans/gtoken.py", line 62, in _update
    code = self.RE_TKK.search(r.text).group(1).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by ddfabbro** [comment]
# See
1. https://github.com/ssut/py-googletrans/issues/234
2. https://stackoverflow.com/questions/52455774/googletrans-stopped-working-with-error-nonetype-object-has-no-attribute-group
